name: Instactf
main: ch.toothwit.instactf.main.Instactf
version: 0.1
author: fredo121, Houston9000
description: Instactf Plugin using Spigot API 
depend: [Lobby,BarAPI]

commands:
  instactf:
    description: Instactf Base Command
    permission: instagib.use
    
permissions:
  instagib.use:
    description: Use Instactf Commands
    default: true
  instagib.admin:
    description: Use Instactf Administration Commands Commands
    default: op